#!/bin/sh
echo "========================"
echo "Unsealing the cradle..."

# Read the incoming commit details
while read _ newrev _; do
  container_id=$(/app/shell_scripts/deploy_bot.sh "$newrev")
  status=$?
  if [ $status -ne 0 ]; then
    echo "Failed to deploy the commit $newrev"
    echo "$container_id"
    exit $status
  fi
done

echo "The seals are removed, the watchman on the watch!"
echo "Watchman ID: $container_id"
echo "========================"

exit 1
