# Generated by Django 5.1.3 on 2024-11-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ssh_key",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="Ключ SSH"
            ),
        ),
    ]
