# Generated by Django 5.1.3 on 2024-11-24 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_ssh_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="ssh_key",
            new_name="ssh_public_key",
        ),
    ]
