# Generated by Django 5.1.3 on 2024-11-29 07:08

import customers.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_alter_sshkey_owner_bot_delete_watchman"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindingRoute",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Создано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Обновлено"
                    ),
                ),
                ("alert_id", models.CharField(max_length=255, verbose_name="Alert ID")),
                (
                    "channel_type",
                    models.IntegerField(
                        choices=[
                            (customers.models.ChannelType["Telegram"], "Telegram"),
                            (customers.models.ChannelType["Webhook"], "Webhook"),
                        ],
                        verbose_name="Feedback channel type",
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram bot token"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram chat ID"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook URL"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bot",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_owner_bot_name"
            ),
        ),
        migrations.AddField(
            model_name="findingroute",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="customers.bot",
                verbose_name="Bot",
            ),
        ),
        migrations.AddField(
            model_name="findingroute",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="findingroute",
            constraint=models.UniqueConstraint(
                fields=("customer", "bot", "alert_id"), name="unique_customer_bot_alert"
            ),
        ),
    ]
