# Generated by Django 5.1.4 on 2024-12-13 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0008_findingroute_bot_unique_owner_bot_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="findingroute",
            name="unique_customer_bot_alert",
        ),
    ]
