# Generated by Django 5.1.4 on 2024-12-19 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0009_remove_findingroute_unique_customer_bot_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="env_vars",
            field=models.JSONField(default=dict, verbose_name="Environment variables"),
        ),
        migrations.AddField(
            model_name="customer",
            name="env_vars",
            field=models.JSONField(default=dict, verbose_name="Environment variables"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="container_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Container ID"
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Joined at"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="sshkey",
            name="key",
            field=models.CharField(max_length=4096, verbose_name="Key content"),
        ),
        migrations.AlterField(
            model_name="sshkey",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Key name"),
        ),
        migrations.AlterField(
            model_name="sshkey",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ssh_keys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
